permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: /dev/ttyACM0
frontend:
  port: 8080
advanced:
  network_key:
    - 193
    - 240
    - 192
    - 158
    - 35
    - 70
    - 16
    - 89
    - 175
    - 232
    - 230
    - 201
    - 48
    - 173
    - 94
    - 124
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0x90395efffe3effe4':
    friendly_name: '0x90395efffe3effe4'
