black:
  max:
  - 115
  - 135
  - 135
  min:
  - 0
  - 0
  - 0
blue:
  max:
  - 130
  - 185
  - 120
  min:
  - 0
  - 126
  - 0
green:
  max:
  - 252
  - 118
  - 255
  min:
  - 0
  - 81
  - 106
red:
  max:
  - 255
  - 255
  - 255
  min:
  - 0
  - 150
  - 130
white:
  max:
  - 255
  - 255
  - 255
  min:
  - 193
  - 0
  - 0
